del " Lems A - Fun\*.lds"
del " Lems B - Tricky\*.lds"
del " Lems C - Taxing\*.lds"
del " Lems D - Mayhem\*.lds"

del "Oh No A - Tame\*.lds"
del "Oh No B - Crazy\*.lds"
del "Oh No C - Wild\*.lds"
del "Oh No D - wicked\*.lds"
del "Oh No E - Havoc\*.lds"

del "Xmas 1991\*.lds"
del "Xmas 1992\*.lds"
del "Xmas A - Frost\*.lds"
del "Xmas B - Hail\*.lds"
del "Xmas C - Flurry\*.lds"
del "Xmas D - Blizz\*.lds"