lemmings_texture_archiver.exe windows_lemmings_terrain_images/Brick/  winlemm_Brick.LTA  F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Bubble/ winlemm_Bubble.LTA F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Fire/   winlemm_Fire.LTA   F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Ice/    winlemm_Ice.LTA    F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Marble/ winlemm_Marble.LTA F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Pillar/ winlemm_Pillar.LTA F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Rock/   winlemm_Rock.LTA   F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Snow/   winlemm_Snow.LTA   F
lemmings_texture_archiver.exe windows_lemmings_terrain_images/Soil/   winlemm_Soil.LTA   F